apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-test-app
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-test-app
  template:
    metadata:
      labels:
        app: gitops-test-app
    spec:
      containers:
      - name: app
        image: hello-app:126
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: BUILD_NUMBER
          value: "latest"
